/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebaingcelular.Presentacion;

import com.mycompany.examen1.Clases.Celular;
import com.mycompany.examen1.Clases.Cliente;
import com.mycompany.examen1.Clases.Recargas;
import com.mycompany.examen1.Persistencias.CelularJpaController;
import com.mycompany.examen1.Persistencias.RecargasJpaController;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Paula Lopez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();
        estadoField = new javax.swing.JTextField();
        saldoField = new javax.swing.JTextField();
        megasField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cedulaField = new javax.swing.JTextField();
        nombresField = new javax.swing.JTextField();
        apellidosField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroRecargaField = new javax.swing.JTextField();
        ingresarNumeroButton = new javax.swing.JButton();
        recargabotton = new javax.swing.JButton();
        IngresaClienteButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ValorRecargaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("CELULAR");

        jLabel2.setText("NUmero:");

        jLabel3.setText("Estado:");

        jLabel4.setText("Saldo:");

        jLabel5.setText("Megas:");

        numeroField.setBackground(new java.awt.Color(153, 153, 153));
        numeroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldActionPerformed(evt);
            }
        });

        estadoField.setBackground(new java.awt.Color(153, 153, 153));
        estadoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoFieldActionPerformed(evt);
            }
        });

        saldoField.setBackground(new java.awt.Color(153, 153, 153));

        megasField.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("CLIENTE");

        jLabel7.setText("Cedula:");

        jLabel8.setText("Nombres:");

        jLabel9.setText("Apellidos:");

        cedulaField.setBackground(new java.awt.Color(153, 153, 153));

        nombresField.setBackground(new java.awt.Color(153, 153, 153));

        apellidosField.setBackground(new java.awt.Color(153, 153, 153));
        apellidosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("RECARGA");

        jLabel11.setText("Valor:");

        numeroRecargaField.setBackground(new java.awt.Color(153, 153, 153));
        numeroRecargaField.setForeground(new java.awt.Color(204, 204, 204));

        ingresarNumeroButton.setBackground(new java.awt.Color(51, 153, 255));
        ingresarNumeroButton.setText("INGRESAR");
        ingresarNumeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNumeroButtonActionPerformed(evt);
            }
        });

        recargabotton.setBackground(new java.awt.Color(51, 153, 255));
        recargabotton.setText("VALIDAR");
        recargabotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargabottonActionPerformed(evt);
            }
        });

        IngresaClienteButton.setBackground(new java.awt.Color(51, 153, 255));
        IngresaClienteButton.setText("INGRESAR");
        IngresaClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresaClienteButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Numero::");

        ValorRecargaField.setBackground(new java.awt.Color(153, 153, 153));
        ValorRecargaField.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(IngresaClienteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cedulaField)
                                    .addComponent(nombresField)
                                    .addComponent(apellidosField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingresarNumeroButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeroField)
                                .addComponent(estadoField)
                                .addComponent(saldoField)
                                .addComponent(megasField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroRecargaField)
                            .addComponent(ValorRecargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(recargabotton)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cedulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(apellidosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(IngresaClienteButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroRecargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ValorRecargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(saldoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recargabotton)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(megasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(ingresarNumeroButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldActionPerformed

    private void estadoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoFieldActionPerformed

    private void apellidosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosFieldActionPerformed

    private void ingresarNumeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNumeroButtonActionPerformed
        String numero = numeroField.getText();
        String estado = estadoField.getText();
        double saldo = Double.parseDouble(saldoField.getText());
        double megas = Double.parseDouble(megasField.getText());

        Celular celular = new Celular();
        celular.setNumero(numero);
        celular.setEstado(estado);
        celular.setSaldo(saldo);
        celular.setMegas(megas);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_Examen1_jar_1.0-SNAPSHOTPU");
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            em.persist(celular);         // Luego el turno (con referencia al vehículo)
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "¡Datos guardados exitosamente!");
        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }

    }//GEN-LAST:event_ingresarNumeroButtonActionPerformed

    private void IngresaClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresaClienteButtonActionPerformed
        String cedula = cedulaField.getText();
        String nombres = nombresField.getText();
        String apellidos = apellidosField.getText();

        Cliente cliente = new Cliente();
        cliente.setCedula(cedula);
        cliente.setNombres(nombres);
        cliente.setApellidos(apellidos);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_Examen1_jar_1.0-SNAPSHOTPU");
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            em.persist(cliente);         // Luego el turno (con referencia al vehículo)
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "¡Datos guardados exitosamente!");
        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_IngresaClienteButtonActionPerformed

    private void recargabottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargabottonActionPerformed
        int valor = Integer.parseInt(ValorRecargaField.getText());
        String numero = numeroRecargaField.getText();

        CelularJpaController celularJpa = new CelularJpaController();
        RecargasJpaController recargaJpa = new RecargasJpaController();

        Celular celular = celularJpa.ValidarCelular(numero);

        if (celular != null) {
            if (!celular.getEstado().equalsIgnoreCase("Activo")) {
                JOptionPane.showMessageDialog(this, "El celular está inactivo. No se puede realizar la recarga.");
                return;
            }

            // Distribución automática: 2/3 para saldo, 1/3 para megas (5 GB por dólar)
            double saldoRecarga = (2.0 / 3.0) * valor;
            double megasRecarga = (1.0 / 3.0) * valor * 5;

            // Registrar la recarga
            Recargas recarga = new Recargas();
            recarga.setValor(valor);
            recarga.setSaldo(saldoRecarga);
            recarga.setMegas(megasRecarga);
            recarga.setCelular(celular);

            try {
                recargaJpa.create(recarga);

                // Actualizar el celular
                celular.setSaldo(celular.getSaldo() + saldoRecarga);
                celular.setMegas(celular.getMegas() + megasRecarga);
                celularJpa.edit(celular);

                JOptionPane.showMessageDialog(this, "✅ Recarga realizada con éxito.\nNuevo saldo: $"
                        + celular.getSaldo() + "\nNuevas megas: " + celular.getMegas() + " GB");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "❌ Error al registrar la recarga: " + e.getMessage());
                e.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(this, "❌ El número no está registrado.");
        }
    

    }//GEN-LAST:event_recargabottonActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresaClienteButton;
    private javax.swing.JTextField ValorRecargaField;
    private javax.swing.JTextField apellidosField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cedulaField;
    private javax.swing.JTextField estadoField;
    private javax.swing.JButton ingresarNumeroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField megasField;
    private javax.swing.JTextField nombresField;
    private javax.swing.JTextField numeroField;
    private javax.swing.JTextField numeroRecargaField;
    private javax.swing.JButton recargabotton;
    private javax.swing.JTextField saldoField;
    // End of variables declaration//GEN-END:variables
}
