/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebaingvehiculos.Inicio;

import com.mycompany.pruebaingvehiculos.Clases.Propietario;
import com.mycompany.pruebaingvehiculos.Clases.Turno;
import com.mycompany.pruebaingvehiculos.Clases.Vehiculo;
import com.mycompany.pruebaingvehiculos.Persistencia.PropietarioJpaController;
import com.mycompany.pruebaingvehiculos.Persistencia.TurnoJpaController;
import com.mycompany.pruebaingvehiculos.Persistencia.VehiculoJpaController;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import java.util.stream.Collectors;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDia = new javax.swing.JLabel();
        jInsertHora = new javax.swing.JTextField();
        jHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInsertCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jInsertNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jInsertApellido = new javax.swing.JTextField();
        jInsertPlaca = new javax.swing.JTextField();
        jInsertMarca = new javax.swing.JTextField();
        jInsertEstado = new javax.swing.JTextField();
        jInsertAnden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCedula = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jApellido = new javax.swing.JLabel();
        jPlaca = new javax.swing.JLabel();
        jMarca = new javax.swing.JLabel();
        jEstado = new javax.swing.JLabel();
        jInsertDia = new javax.swing.JTextField();
        jAnden = new javax.swing.JLabel();
        jIngresarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDia.setText("Dia:");

        jInsertHora.setBackground(new java.awt.Color(153, 153, 153));

        jHora.setText("Hora:");

        jLabel2.setText("PROPIETARIO");

        jInsertCedula.setBackground(new java.awt.Color(153, 153, 153));
        jInsertCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertCedulaActionPerformed(evt);
            }
        });

        jLabel3.setText("VEHÍCULO");

        jInsertNombre.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setText("TURNO");

        jInsertApellido.setBackground(new java.awt.Color(153, 153, 153));

        jInsertPlaca.setBackground(new java.awt.Color(153, 153, 153));
        jInsertPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertPlacaActionPerformed(evt);
            }
        });

        jInsertMarca.setBackground(new java.awt.Color(153, 153, 153));

        jInsertEstado.setBackground(new java.awt.Color(153, 153, 153));

        jInsertAnden.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("TURNOS DE VEHÍCULOS");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jCedula.setText("Cedula:");

        jNombre.setText("Nombre:");

        jApellido.setText("Apellido:");

        jPlaca.setText("Placa:");

        jMarca.setText("Marca:");

        jEstado.setText("Estado:");

        jInsertDia.setBackground(new java.awt.Color(153, 153, 153));
        jInsertDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertDiaActionPerformed(evt);
            }
        });

        jAnden.setText("Anden:");

        jIngresarTurno.setBackground(new java.awt.Color(51, 153, 255));
        jIngresarTurno.setText("Ingresar turno");
        jIngresarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMarca)
                                    .addComponent(jPlaca))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jEstado)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jInsertPlaca)
                            .addComponent(jInsertMarca)
                            .addComponent(jInsertEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAnden)
                            .addComponent(jDia)
                            .addComponent(jHora))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jInsertDia)
                            .addComponent(jInsertHora)
                            .addComponent(jInsertAnden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(jIngresarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCedula)
                                    .addComponent(jNombre)
                                    .addComponent(jApellido))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jInsertNombre)
                                    .addComponent(jInsertApellido)
                                    .addComponent(jInsertCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPlaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMarca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInsertEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEstado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAnden)
                                .addGap(24, 24, 24)
                                .addComponent(jDia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jHora))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jInsertAnden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInsertDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInsertHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIngresarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInsertCedulaActionPerformed

    private void jInsertPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInsertPlacaActionPerformed

    private void jIngresarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarTurnoActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_PruebaIngVehiculos_jar_1.0-SNAPSHOTPU");

        // Controllers
        PropietarioJpaController propCtrl = new PropietarioJpaController();
        VehiculoJpaController vehiCtrl = new VehiculoJpaController();
        TurnoJpaController turnoCtrl = new TurnoJpaController();

        try {
            // 1. Crear Propietario
            Propietario prop = new Propietario();
            prop.setCedula(jInsertCedula.getText());
            prop.setNombre(jInsertNombre.getText());
            prop.setApellido(jInsertApellido.getText());
            propCtrl.create(prop);

            // 2. Crear Vehículo
            Vehiculo vehi = new Vehiculo();
            vehi.setPlaca(jInsertPlaca.getText());
            vehi.setMarca(jInsertMarca.getText());
            vehi.setEstado(jInsertEstado.getText());
            vehi.setPropietario(prop);
            vehiCtrl.create(vehi);

            // 3. Obtener datos del turno
            int anden = Integer.parseInt(jInsertAnden.getText());
            Date dia = Date.valueOf(jInsertDia.getText()); // formato: yyyy-MM-dd
            Time hora = Time.valueOf(jInsertHora.getText()); // formato: HH:mm:ss

            // 4. Validar turnos existentes de este vehículo
            List<Turno> turnosVehiculo = turnoCtrl.findTurnoEntities().stream()
                    .filter(t -> t.getVehiculo().getPlaca().equals(vehi.getPlaca()))
                    .collect(Collectors.toList());

            boolean mismoDia = turnosVehiculo.stream()
                    .anyMatch(t -> t.getDia().equals(dia));

            boolean mismoDiaYAnden = turnosVehiculo.stream()
                    .anyMatch(t -> t.getDia().equals(dia) && t.getAnden() == anden);

            if (mismoDia) {
                JOptionPane.showMessageDialog(this, "Error: El vehículo ya tiene un turno ese día.");
                return;
            }

            if (mismoDiaYAnden) {
                JOptionPane.showMessageDialog(this, "Error: El vehículo ya tiene un turno en ese andén ese mismo día.");
                return;
            }

            // 5. Crear Turno
            Turno turno = new Turno();
            turno.setAnden(anden);
            turno.setDia(dia);
            turno.setHora(hora);
            turno.setVehiculo(vehi);
            turnoCtrl.create(turno);

            JOptionPane.showMessageDialog(this, "Turno registrado correctamente.");
        } catch (Exception e) {
            e.printStackTrace(); // esto mostrará el error completo en consola
            JOptionPane.showMessageDialog(this, "Error general: " + e.toString());

        }
    }//GEN-LAST:event_jIngresarTurnoActionPerformed

    private void jInsertDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDiaActionPerformed
        // TODO add your handling code here:
        String textoDia = jInsertDia.getText();
        System.out.println("Día ingresado: " + textoDia); // Esto te ayudará a depurar

        try {
            Date dia = Date.valueOf(textoDia);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Debe ser yyyy-MM-dd");
            return;
        }
    }//GEN-LAST:event_jInsertDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAnden;
    private javax.swing.JLabel jApellido;
    private javax.swing.JLabel jCedula;
    private javax.swing.JLabel jDia;
    private javax.swing.JLabel jEstado;
    private javax.swing.JLabel jHora;
    private javax.swing.JButton jIngresarTurno;
    private javax.swing.JTextField jInsertAnden;
    private javax.swing.JTextField jInsertApellido;
    private javax.swing.JTextField jInsertCedula;
    private javax.swing.JTextField jInsertDia;
    private javax.swing.JTextField jInsertEstado;
    private javax.swing.JTextField jInsertHora;
    private javax.swing.JTextField jInsertMarca;
    private javax.swing.JTextField jInsertNombre;
    private javax.swing.JTextField jInsertPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPlaca;
    // End of variables declaration//GEN-END:variables
}
